import React, { useState, useEffect } from 'react';
import { collection, onSnapshot, query, orderBy, limit } from 'firebase/firestore';
import { db } from '../config/firebase';
import { TrendingUp, TrendingDown, DollarSign, ArrowUpCircle, ArrowDownCircle } from 'lucide-react';

export const CapitalFlowDashboard: React.FC = () => {
  const [capitalData, setCapitalData] = useState<any>(null);
  const [recentTransactions, setRecentTransactions] = useState<any[]>([]);

  useEffect(() => {
    const unsubCapital = onSnapshot(
      query(collection(db, 'capital_summary'), orderBy('timestamp', 'desc'), limit(1)),
      (snapshot) => {
        if (!snapshot.empty) {
          setCapitalData({ id: snapshot.docs[0].id, ...snapshot.docs[0].data() });
        }
      }
    );

    const unsubTransactions = onSnapshot(
      query(collection(db, 'financial'), orderBy('date', 'desc'), limit(10)),
      (snapshot) => {
        setRecentTransactions(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })));
      }
    );

    return () => {
      unsubCapital();
      unsubTransactions();
    };
  }, []);

  if (!capitalData) return null;

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Capital In</p>
              <p className="text-2xl font-bold text-green-600">
                KSh {capitalData.capitalIn?.toLocaleString() || 0}
              </p>
            </div>
            <div className="bg-green-100 p-3 rounded-lg">
              <ArrowUpCircle className="h-6 w-6 text-green-600" />
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Capital Out</p>
              <p className="text-2xl font-bold text-red-600">
                KSh {capitalData.capitalOut?.toLocaleString() || 0}
              </p>
            </div>
            <div className="bg-red-100 p-3 rounded-lg">
              <ArrowDownCircle className="h-6 w-6 text-red-600" />
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Net Capital</p>
              <p className={`text-2xl font-bold ${capitalData.netCapital >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                KSh {capitalData.netCapital?.toLocaleString() || 0}
              </p>
            </div>
            <div className={`${capitalData.netCapital >= 0 ? 'bg-green-100' : 'bg-red-100'} p-3 rounded-lg`}>
              {capitalData.netCapital >= 0 ? (
                <TrendingUp className="h-6 w-6 text-green-600" />
              ) : (
                <TrendingDown className="h-6 w-6 text-red-600" />
              )}
            </div>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-lg shadow p-6">
        <h3 className="text-lg font-semibold mb-4">Recent Transactions</h3>
        <div className="space-y-2">
          {recentTransactions.map((transaction: any) => (
            <div key={transaction.id} className="flex items-center justify-between p-3 border rounded-lg hover:bg-gray-50">
              <div className="flex items-center space-x-3">
                <div className={`p-2 rounded-lg ${transaction.type === 'income' ? 'bg-green-100' : 'bg-red-100'}`}>
                  {transaction.type === 'income' ? (
                    <ArrowUpCircle className="h-4 w-4 text-green-600" />
                  ) : (
                    <ArrowDownCircle className="h-4 w-4 text-red-600" />
                  )}
                </div>
                <div>
                  <p className="font-medium text-sm">{transaction.description}</p>
                  <p className="text-xs text-gray-500">{transaction.category}</p>
                  {transaction.autoGenerated && (
                    <span className="text-xs bg-blue-100 text-blue-800 px-2 py-0.5 rounded">Auto</span>
                  )}
                </div>
              </div>
              <div className="text-right">
                <p className={`font-semibold ${transaction.type === 'income' ? 'text-green-600' : 'text-red-600'}`}>
                  {transaction.type === 'income' ? '+' : '-'}KSh {transaction.amount?.toLocaleString() || 0}
                </p>
                <p className="text-xs text-gray-500">
                  {transaction.date?.toDate?.()?.toLocaleDateString() || 'N/A'}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
